<a href="https://colab.research.google.com/github/bmreiniger/datascience.stackexchange/blob/master/56676.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from keras.models import Model
from keras.layers import Input, Dense, Dropout
from keras.optimizers import Adam
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping

n = 8

# Create an input array of 50,000 samples of n random numbers each
x = np.random.randint(0, 100, size=(50000, n))

# And a one-hot encoded target denoting the index of the maximum of the inputs
y = to_categorical(np.argmax(x, axis=1), num_classes=n)

# Split into training and testing datasets
x_train, x_test, y_train, y_test = train_test_split(x, y)

print(x_train[:10])
print(y_train[:10])

Using TensorFlow backend.


[[55 85 52 55 65 70 18 35]
 [42 27 77 81 69 63 71  4]
 [15 54 86 88 40 74 60  7]
 [ 5 17 34 57  0 81 45 94]
 [ 5 36 34 68  6 95 40 40]
 [20 33 26  4  6 74 28 95]
 [72 38 67 22 78 98 37 65]
 [98 35  4  2 18 33 55 81]
 [22 12 22 77 98 96 92 30]
 [ 5 92 17 24 96 24  3 18]]
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [3]:
i = Input(shape=(n, ))
a = Dense(int(n**2), activation='sigmoid')(i)
o = Dense(n, activation='sigmoid')(a)

model = Model(inputs=i, outputs=o)

adam = Adam(lr=.01, decay=0.005)
model.compile(optimizer=adam, loss='categorical_crossentropy')

model.fit(x_train, y_train, epochs=30, batch_size=8, validation_data=[x_test, y_test])

print(np.where(np.argmax(model.predict(x_test), axis=1) == np.argmax(y_test, axis=1), 1, 0).mean())

W0803 21:44:44.864091 140080907765632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0803 21:44:44.914702 140080907765632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0803 21:44:44.925900 140080907765632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0803 21:44:44.979133 140080907765632 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0803 21:44:44.993714 140080907765632 deprecation_wrappe

Train on 37500 samples, validate on 12500 samples
Epoch 1/30
37500/37500 [==============================] - 6s 170us/step - loss: 0.6164 - val_loss: 0.5131
Epoch 2/30
37500/37500 [==============================] - 6s 153us/step - loss: 0.4854 - val_loss: 0.4717
Epoch 3/30
37500/37500 [==============================] - 6s 152us/step - loss: 0.4588 - val_loss: 0.4601
Epoch 4/30
37500/37500 [==============================] - 6s 152us/step - loss: 0.4437 - val_loss: 0.4488
Epoch 5/30
37500/37500 [==============================] - 6s 152us/step - loss: 0.4348 - val_loss: 0.4432
Epoch 6/30
37500/37500 [==============================] - 6s 150us/step - loss: 0.4275 - val_loss: 0.4403
Epoch 7/30
37500/37500 [==============================] - 6s 150us/step - loss: 0.4227 - val_loss: 0.4346
Epoch 8/30
37500/37500 [==============================] - 6s 154us/step - loss: 0.4180 - val_loss: 0.4317
Epoch 9/30
37500/37500 [==============================] - 6s 154us/step - loss: 0.4143 - val_loss: 0.4

In [4]:
print(np.where(np.argmax(model.predict(x_test), axis=1) == np.argmax(y_test, axis=1), 1, 0).mean())

0.83792


In [5]:
x_big = np.random.randint(100, 200, size=(1000, n))
y_big = to_categorical(np.argmax(x_big, axis=1), num_classes=n)
print(np.where(np.argmax(model.predict(x_big), axis=1) == np.argmax(y_big, axis=1), 1, 0).mean())

0.698


In [3]:
# Now use inputs between +- 1
x_new = (np.random.random(size=(50000, n)).reshape(50000,n) -0.5)*2
y_new = to_categorical(np.argmax(x_new, axis=1), num_classes=n)
x_new_train, x_new_test, y_new_train, y_new_test = train_test_split(x_new, y_new)

i = Input(shape=(n, ))
a = Dense(int(n**2), activation='sigmoid')(i)
o = Dense(n, activation='sigmoid')(a)
model = Model(inputs=i, outputs=o)

adam = Adam(lr=.0003)
model.compile(optimizer=adam, loss='categorical_crossentropy')

model.fit(x_new_train, y_new_train, epochs=30, batch_size=8, validation_data=[x_new_test, y_new_test])

print(np.where(np.argmax(model.predict(x_new_test), axis=1) == np.argmax(y_new_test, axis=1), 1, 0).mean())

W0804 02:48:32.465422 139816700307328 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0804 02:48:32.502084 139816700307328 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0804 02:48:32.511049 139816700307328 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0804 02:48:32.557210 139816700307328 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0804 02:48:32.571322 139816700307328 deprecation_wrappe

Train on 37500 samples, validate on 12500 samples
Epoch 1/30
37500/37500 [==============================] - 6s 163us/step - loss: 1.4861 - val_loss: 0.9815
Epoch 2/30
37500/37500 [==============================] - 6s 149us/step - loss: 0.7773 - val_loss: 0.6349
Epoch 3/30
37500/37500 [==============================] - 6s 150us/step - loss: 0.5636 - val_loss: 0.5023
Epoch 4/30
37500/37500 [==============================] - 6s 148us/step - loss: 0.4661 - val_loss: 0.4294
Epoch 5/30
37500/37500 [==============================] - 6s 149us/step - loss: 0.4084 - val_loss: 0.3838
Epoch 6/30
37500/37500 [==============================] - 6s 148us/step - loss: 0.3695 - val_loss: 0.3514
Epoch 7/30
37500/37500 [==============================] - 6s 149us/step - loss: 0.3408 - val_loss: 0.3261
Epoch 8/30
37500/37500 [==============================] - 5s 147us/step - loss: 0.3187 - val_loss: 0.3077
Epoch 9/30
37500/37500 [==============================] - 6s 148us/step - loss: 0.3008 - val_loss: 0.2

In [7]:
print(x_new_test[:10].round(2))
print(model.predict(x_new_test[:10]).round(2))

[[-0.45  0.32  0.12 -0.12  0.97 -0.23 -0.15 -0.12]
 [-0.97 -0.62  0.48  0.74  0.76 -0.67 -0.21  0.89]
 [-0.75 -0.95  0.39  0.94  0.67 -0.46 -0.05  0.31]
 [ 0.78 -0.98 -0.81  0.55 -0.27 -0.36  0.55 -0.84]
 [-0.57  0.29  0.49  0.65 -0.05 -0.83  0.83  0.87]
 [-0.56 -0.67 -0.12  0.38 -0.37  0.88  0.19 -0.94]
 [-0.26  0.25 -0.84 -0.6  -0.91 -0.68  0.52 -0.7 ]
 [ 0.62  0.08  0.84 -0.14  0.84  0.88  0.02  0.49]
 [-0.93  0.03  0.11 -0.01 -0.18 -0.09 -0.92  0.55]
 [ 0.32  0.7   1.    0.84  0.24  0.36 -0.32  0.07]]
[[0.   0.   0.   0.   0.62 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.02 0.   0.   0.   0.  ]
 [0.03 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.51 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.16 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.  ]]


In [9]:
x_big = np.random.randint(100, 200, size=(1000, n))
y_big = to_categorical(np.argmax(x_big, axis=1), num_classes=n)
print(np.where(np.argmax(model.predict(x_big), axis=1) == np.argmax(y_big, axis=1), 1, 0).mean())

0.758


In [12]:
model.layers[1].get_weights()

[array([[ 0.87956274,  1.1978772 ,  0.46450382,  0.7307273 , -0.6984442 ,
         -1.3457828 ,  0.09478747,  1.0741805 , -1.507459  , -1.2638655 ,
         -1.4725051 , -1.1914657 ,  1.8128251 , -0.6159663 , -1.0193957 ,
         -1.6737666 , -2.066794  ,  1.4463797 , -1.0314105 , -0.9695291 ,
         -0.8354103 , -2.0047107 ,  0.8812803 , -0.1561685 , -1.5060434 ,
         -1.0683078 ,  1.3409086 , -1.385963  ,  1.1036689 ,  0.6200164 ,
         -0.5659612 ,  1.8297471 , -1.8397077 , -0.5272667 ,  1.8492919 ,
          0.49020806,  1.58267   ,  0.31083837, -1.6804259 ,  0.9360691 ,
          1.4568046 , -0.38561386,  1.3096594 ,  1.060757  , -0.3548948 ,
          1.2196922 , -1.7746696 , -1.3284345 , -2.433707  ,  1.5120528 ,
         -0.76299334, -1.7531025 ,  0.02317628,  0.77569026, -1.7030356 ,
          0.80639404,  0.18325688, -2.1653275 ,  0.8659146 , -1.796664  ,
          1.807544  ,  1.438966  ,  1.1653038 ,  1.4669718 ],
        [ 0.81185657, -1.9098729 ,  1.2062043 , -1